// Generated by CoffeeScript 1.6.1
(function() {
  var $, $curr, $dissolvers, ANIMATION_DURATION, ANIMATION_INTERVAL, NUM_DISSOLVE_IMAGES, doDissolving, isDissolving, isMouseOver, numDissolveLoaded, onClickDissolveControl, prepareDissolving, timer;

  $ = this.jQuery;

  numDissolveLoaded = 1;

  NUM_DISSOLVE_IMAGES = 3;

  timer = null;

  isDissolving = false;

  $dissolvers = $('.dissolve-blue, .dissolve-orange, .dissolve-gray');

  $curr = null;

  ANIMATION_INTERVAL = 5000;

  ANIMATION_DURATION = 2000;

  onClickDissolveControl = function(e) {
    var ix;
    if (isDissolving) {
      return;
    }
    ix = $('.dissolve-control').index(e.currentTarget);
    if (ix === $dissolvers.index($curr)) {
      return;
    }
    clearTimeout(timer);
    return doDissolving($dissolvers.eq(ix));
  };

  doDissolving = function($next) {
    var currix, nextix, nextnextix;
    if (isDissolving) {
      return;
    }
    if ($next.get(0) === $curr.get(0)) {
      return;
    }
    isDissolving = true;
    currix = $dissolvers.index($curr);
    nextix = $dissolvers.index($next);
    nextnextix = nextix + 1 >= NUM_DISSOLVE_IMAGES ? 0 : nextix + 1;
    $('.dissolve-control').eq(currix).removeClass('is-active').end().eq(nextix).addClass('is-active');
    $curr.fadeOut(ANIMATION_DURATION, 'swing');
    return $next.fadeIn(ANIMATION_DURATION, 'swing', function() {
      $curr.addClass('hide');
      $next.removeClass('hide');
      isDissolving = false;
      timer = setTimeout($.proxy(doDissolving, window, $dissolvers.eq(nextnextix)), ANIMATION_INTERVAL);
      return $curr = $next;
    });
  };

  prepareDissolving = function() {
    $('.dissolve-control-group').removeClass('hide').find('.dissolve-control').on('click', onClickDissolveControl);
    $curr = $('.dissolve-blue');
    return doDissolving($('.dissolve-orange'));
  };

  $('.dissolve-orange img, .dissolve-gray img').each(function(ix, elem) {
    var $this;
    $this = $(elem);
    return $this.attr('src', $this.attr('data-src')).one('load', function() {
      numDissolveLoaded += 1;
      if (numDissolveLoaded >= NUM_DISSOLVE_IMAGES) {
        return prepareDissolving();
      }
    });
  });

  isMouseOver = false;

  $('.is-solutions').on('mouseover', function(e) {
    var $this;
    $this = $(e.currentTarget);
    $('.nav-menu-body', $this).css('display', 'block');
    return isMouseOver = true;
  }).on('mouseout', function(e) {
    var $this, hideMenu;
    $this = $(e.currentTarget);
    isMouseOver = false;
    hideMenu = function() {
      if (!isMouseOver) {
        return $('.is-solutions .nav-menu-body').css('display', 'none');
      }
    };
    return setTimeout(hideMenu, 100);
  });

}).call(this);
