// Generated by CoffeeScript 1.6.1
(function() {
  var $;

  $ = this.jQuery;

  $.getJSON('/js/event.json', function(response) {
    var html, res, _i, _len;
    html = '';
    for (_i = 0, _len = response.length; _i < _len; _i++) {
      res = response[_i];
      html += "<div class=\"doc-body-event\">\n	<div class=\"doc-body-event-date\">" + res.date + "</div>\n	<h3 class=\"doc-body-event-title\">" + res.title + "</h3>\n	<a href=\"" + res.link + "\" class=\"doc-body-event-link\">" + res.visit + "</a> or <a href=\"mailto:hello@appier.com\" class=\"doc-body-event-link\">Request a meeting</a>\n	<a href=\"" + res.link + "\"><img src=\"" + res.image + "\" class=\"doc-body-event-image\"></a>\n</div>";
    }
    return $('.doc-body').append(html);
  });

}).call(this);
