// Generated by CoffeeScript 1.6.1
(function() {
  var setMenu;

  setMenu = function(cls) {
    var isMouseOver;
    isMouseOver = false;
    return $(cls).on('mouseover', function(e) {
      var $this;
      $this = $(e.currentTarget);
      $('.nav-menu-body', $this).removeClass('hide');
      return isMouseOver = true;
    }).on('mouseout', function(e) {
      var $this, hideMenu;
      $this = $(e.currentTarget);
      isMouseOver = false;
      hideMenu = function() {
        if (!isMouseOver) {
          return $("" + cls + " .nav-menu-body").addClass('hide');
        }
      };
      return setTimeout(hideMenu, 100);
    });
  };

  setMenu('.is-solutions');

  setMenu('.is-about');

}).call(this);
