// Generated by CoffeeScript 1.4.0
(function() {
  var $;

  $ = this.jQuery;

  $('.doc-body-tabbable').on('click', function(e) {
    var $this;
    $this = $(e.currentTarget);
    if ($this.hasClass('is-active')) {
      return;
    }
    $('.doc-body-tabbable').toggleClass('is-active');
    return $('.doc-body-advertiser, .doc-body-publisher').toggleClass('hide');
  });

}).call(this);
