// Generated by CoffeeScript 1.6.1
(function() {
  var NewsEventsView;

  NewsEventsView = Backbone.View.extend({
    el: "#layout-news-events",
    TEMPLATE: "<img src=\"image/index/Q.png\" class=\"doc-body-email\" alt=\"hello@appier.com\">\n<img src=\"image/index/2013.png\" class=\"doc-body-gdc\" alt=\"2013 GDC Booth #208\">\n<div class=\"doc-body-news-events\">\n  <a class=\"fb-link\" href=\"https://www.facebook.com/AppierNetwork\"></a>\n  <a class=\"tw-link\" href=\"https://twitter.com/GoAppier\"></a>\n\n  <div class=\"doc-body-news\">\n    <div class=\"doc-body-news-tag\"></div>\n  </div>\n\n  <div class=\"doc-body-events\">\n    <div class=\"doc-body-events-tag\"></div>\n  </div>\n</div>",
    render: function() {
      this.$el.html(NewsEventsView.prototype.TEMPLATE);
      return this;
    }
  });

  window.view = new NewsEventsView().render();

}).call(this);
